from fastapi.testclient import TestClient
from app.main import app

client = TestClient(app)

def test_logging_middleware_headers():
    """Verify that the logging middleware injects tracking headers into responses."""
    response = client.get("/health")
    
    # Ensure health check succeeds
    assert response.status_code == 200
    
    # Check that tracking headers generated by middleware exist
    assert "x-request-id" in response.headers
    assert "x-process-time-ms" in response.headers